# Identificación del proyecto
sonar.projectKey=Backend_Laravel_T
sonar.projectName=Backend_Laravel_Turismo
sonar.projectVersion=1.0.${BUILD_NUMBER}

# Código fuente a analizar (incluye todas las carpetas de producción)
sonar.sources=app,database,routes

# Carpeta de pruebas (para que se incluya en el análisis)
sonar.tests=tests

# Archivos y carpetas a excluir del análisis
sonar.exclusions=vendor/**,storage/**,node_modules/**,public/**,.env

# Codificación
sonar.sourceEncoding=UTF-8

# Lenguaje
sonar.language=php

# Cobertura de pruebas generada por PHPUnit en formato Clover
sonar.php.coverage.reportPaths=storage/coverage/clover.xml

# Servidor SonarQube
sonar.host.url=http://host.docker.internal:9000

# Token de autenticación (asegúrate de que este sea válido)
sonar.token=squ_b9ebb805459783f90dfd89df2e3386dbec425b1c

# Mostrar todo como nuevo código (útil durante desarrollo inicial)
sonar.newCode.period=1

# Para incluir todos los archivos PHP en el análisis
sonar.inclusions=**/*.php

# Para incluir solo los archivos de prueba, si deseas
sonar.test.inclusions=tests/**/*.php  # Para incluir solo los archivos de prueba

# Opcional: Excluir otros tipos de archivos si no quieres analizarlos
sonar.test.exclusions=tests/fixtures/**  # Si tienes datos o fixtures en la carpeta de pruebas
